### ISSUE TITLE
大商所返回412错误

### ISSUE THREAD

**Issue by ghost** [yuany3721/DCEData#1]
**首先感谢分享。借用你的代码写了四大交易所的日数据爬取。**

**这两天发现大商所这一部分加密了数据？ 下载你的代码返回的是**

C:\Users\MX\Downloads\DCEData-main>python main.py -v 棕榈油 -t 期权 20210104 20210108
requesting: 2021.0.4_p
error while get html (code:412)
requesting: 2021.0.5_p
error while get html (code:412)
requesting: 2021.0.6_p
error while get html (code:412)
requesting: 2021.0.7_p
error while get html (code:412)

**然后我自己那边用的是requests.post 做的。现在返回一个没有表格的html文件**

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta content="uIt3JwRDcnSazxHPlZTlHYB9De.3evTxfLefVAVDWvCh2h0rgGdhK.cX_1tBGFS9z7_tP.uzkYDtCUXpVLfwz2SKcrdrDrt4HZBBrOqfdeRJYild6PY42I0MLaWlkemaTH2XoSOzvqrsBE9LzftPA_hyfSj30oL05KDwkJrLduDDSkzOjw0YicOLJCYkm2UM2lzhwCYWXJsoALuS3NfRQHilAW8fPx6RT9K0gHtBE8_svZgkLlO3ejTVv0VDNb41oIz48Axf7.uhvSPmy.bbVaGFmmOfge9RHxZDIPf1TvNSzB5VVUIaEMwaYc2hXsnCx_4QvIDfBGi9U0255up6tZa65t4aN2O0kYPYFANcl8Vj_x4jDwa_DZEt60eofu6Mivaz_dtoB02wPdfpGDYYsLPm3tGcjKYYszO2WzCTUc5ua8NA5In7yq" r="m"><script type="text/javascript" r='m'>$_ts=window['$_ts'];if(!$_ts)$_ts={};$_ts.nsd=53178;$_ts.cd="qhqZrpAloPEqmq9EJGWDWAAPqrAxcs3qoAGkqk3DJGQDis3mxGGlo1EqmalCrG3yJGVDWAECqq3SrAWqJG3Cra3yJGAbcAAGEGqUru3lrO9Pqk3cJGWDis3DxulkEGqCrk3mrO9CqP3trq0Pqk3qJGlDis3lrOlmEGqTcA7Crf0EEGqCrk3mrO9CEA3Sr1EqJG3VcpV.xG7lDqWqJGqCqA3yJGADWAVPqk3cJGWDmu3qxPtGqsVSrAVnJFqOkNKV5xR16ybCxrH5uQmTpG6.6jcImSrTwu2SjWEVAoGkrkAorqDfhqHLUvabJQTVFuJSHCfAyK2q1T0NMmO1sCxhwcV5K7yCMC9NFUmzucezQD2.tDdYMCZNF6xLM3Szwb2NKPGOboNvFkJWFDInKKZeUorEWipHAsW0pP345CTCFK9.FvsWMne.QDzLhQyCMC9NFUmzucezQD2.K1Cc3lpSADea8Eg6FbyXJ2yk9sRfJmT5AniFKDTaFK7LMeYBMn2.QbfzODTCFK9.FvsWMne.QDzLUEafwKedVlwHblrAWUShFOM2sm3aJ2R8AEEyKDzaFCGzuvRBF12NQK6WhCTaFK7LMeYBMn2.QbfzdUgBF6r.Fmnjq_2nFC96KWQCMOyqFurb0YxEYOywQbCVMDzq1kaeFBfFYTxtFsZTuVrYwmSt1O.CMTmoUoVeWQzP1ka5RYlC5Oq_3lNUw2oVilZC3K2XMXNTWCTqIueHSVwn12wYUbhiVYl.JORbWNWnJnzBwkeST0fMUmTBHYOoAOA.JORbWNWnJnzBwkey9oVCwTpCwKOFwv35Rlf01JR91CxaJ9NMbuJj1brHMvH3RbpOFAQlqFluqaA0rSRNTowuHu30JkFVJOQ6Wkl5iRqkrs30RsQn9AWqWuEurqXpJslTJsWeixVTqalSJkluLriUlrD9GA6uys.EThi7nmawqSYe.3IK71n_Xa1vrat2rGArr1QxjxT7EfMr.IrZ.FzQuhzrSt20X5WsM22Oj9tXWPqKcGAh9OV4JsEuWuPKWAWlJAQiWx3CiuQ6Js0a2AWLJ9Zuwok6sP0CVUJZQwE0QmroIC2cTDgTQ0SiAbsg89YvVCYN3xAz1vxsVAArLqE6rAA6rqcUqaWmrAQqULp2WaVrKcq20aWoKPm.QAD9Ucw.AAQDWyEkqs3Z";if($_ts.lcd)$_ts.lcd();</script><script type="text/javascript" charset="utf-8" src="/bU7Z39eOPrPt/NeDqORRZcnRR.31b3314.js" r='m'></script></head>
<body>
</body>
</html>
<script type="text/javascript" r='m'>_$n$();</script>

**感谢**

**Comment by yuany3721** [comment]
非常开心该项目能够帮助到您（也许？），以下是对您遇到问题的解答：

1. 有关412错误

> **412 Precondition Failed (RFC 7232)**
> The server does not meet one of the preconditions that the requester put on the request header fields.

在以下尝试复现过程中解决（伪）：

    1. 使用您发现bug的命令 `python main.py -v 棕榈油 -t 期权 20210104 20210108` 运行程序，得到和您一样的412错误代码
    2. 直接使用浏览器（Chrome 103.0.5060.114 64bit）访问 [http://www.dce.com.cn/publicweb/quotesdata/dayQuotesCh.html](http://www.dce.com.cn/publicweb/quotesdata/dayQuotesCh.html) 
    3. 手动选择（棕榈油、期权、20210104）并查看手动访问时的请求信息，未发现异常
    4. 回到命令行再次执行该命令，程序可以正常运行得到期望结果（因为那几天实际上没有数据，所以表中也无数据，改变日期后可以正常获取数据）

目前暂不清楚其preconditions设置和执行原理。

如果您仍遇到这样的问题，请更详细地描述您遇到问题时的具体场景和环境。

2. 有关数据 

不清楚您的request.post获取的是什么内容，按照上述过程，网站应该没有添加新的数据加密措施。

如果您仍需修改执行您的代码，请将您的完整代码贴出来，并更确切地描述您遇到的问题。
